### ISSUE TITLE
/baltop causes major server lag for ~5-10 seconds

### ISSUE THREAD

**Issue by Trnrr** [Erigitic/TotalEconomy#353] opened 2019-07-30 18:51 UTC
Sponge Version:  spongeforge-1.12.2-2768-7.1.6-RC3616
Forge Version:  forge-1.12.2-14.23.5.2807
Total Economy Version:  1.8.1

### Description of issue
When anyone uses /baltop it lags hard for like 5-10 seconds.

### Steps to reproduce
type /baltop

I found https://github.com/Erigitic/TotalEconomy/issues/270 & https://github.com/Erigitic/TotalEconomy/issues/349 and did a quick skim but I couldn't find how to fix it.

Is it fixed by building 1.8.2 that is said in the second issue linked?

Sorry for the lack of info/explanation, I'm currently on a long car ride and on phone. I have just disabled the command for now, but would just like to be pointed in the direction on how to fix it. That way when I get home I can stop the lag :P

**Comment by Erigitic** [comment] 2019-07-30 19:14
I'm not sure if a fix has been made for this yet. The best option at the moment is to just disable the command. I'm not to fond of this command so it might be something we eventually remove, though I'll leave that open for discussion. Also, since this is a duplicate of #349 I'm going to close it and direct further discussion there.

**Closed by Erigitic** 2019-07-30 19:14 UTC

**Comment by Trnrr** [comment] 2019-07-30 19:39
Thanks for the quick response. I will subscribe to that post and keep watch on it. If possible it would be nice if the command stayed and was eventually fixed. It's not too big of issue though, I will just keep it disabled now. It just adds a little more competition to the server :)

**Comment by MarkL4YG** [comment] 2019-07-31 15:06
You could try out the suggested build and kindly poke @Erigitic to release the bugfix release :stuck_out_tongue_winking_eye:
