### ISSUE TITLE
Introduce AdminShop and PlayerShop into the new update.

### ISSUE THREAD

**Issue by COLDYY1** [Erigitic/TotalEconomy#211] opened 2017-10-01 15:55 UTC
This is no suggestion or in any way a compelling one. This is just a simple sentence asking if you were supposed to introduce AdminShop and PlayerShop into this new and upcomming release for API 7.0.0. I thought it might be a bit fun to include it in API 7.0.0, since these new features may be useful to the new API. : D

Kind Regards,
Daniel (COLDYY1)

**Comment by MarkL4YG** [comment] 2017-10-01 17:30
I don't really get why the first official API 7 release would have any special reason to be the Shop release aside from the shops being finished anyways.  
As far as I know there shouldn't be significant differences between API 5, 6 and 7 regarding shops as the biggest change in 7 is the cause tracking system.  

Anyways, you can expect shops to be released as soon as @Erigitic feels like they're stable enough for a release. (There may be a pre-release though)  
Being interested too: @Erigitic how _is_ shop development going? I've haven't had the time to check how the code progressed so far.

**Comment by Erigitic** [comment] 2017-10-03 00:06
Development is going great on shops. Nearing completion, and there will be a pre release when they are at a stable enough point. Depending on how long API 7 stays experimental, it'll most likely be released using API 6 first.

**Comment by COLDYY1** [comment] 2017-10-03 06:37
Are you aiming on a sign-based server shop system ? ...

Kind Regards,
Daniel (COLDYY1)

**Comment by Erigitic** [comment] 2017-10-04 00:06
At the moment, it's only going to be chest shops. Sign shops will probably be added some day though.

**Comment by Erigitic** [comment] 2017-10-12 04:22
Closing this issue in favor of https://github.com/Erigitic/TotalEconomy/issues/50.

**Closed by Erigitic** 2017-10-12 04:22 UTC
