### ISSUE TITLE
Cant add new block breaking/placing without the plugin losing the set

### ISSUE THREAD

**Issue by mrmauwurf** [Erigitic/TotalEconomy#259] opened 2018-04-12 09:34 UTC
Sponge Version:  1.12.2-2611-7.1.0-BETA-2990
Forge Version:  1.12.2 - 14.23.2.2618
Total Economy Version:  1.8.0

### Description of issue
I added some wood and some saplings to the jobsets.conf to lumberjack and farmer after i have done that the plugin just dont know one set every set is mission i checken the {} but for me it look like everything is in good shape.
### Console errors
[Server thread/WARN] [totaleconomy]: Job farmer has the nonexistent set "crops"
example happens with all other jobs as well.
### Steps to reproduce
When i just add the normal jobsets.conf back and dont use my own it works fine but when i use my one with added blocks for the jobs it just say to every job! Even if i didnt add one thing to a set that error shows up for me. So i think i just use a mod that is not supported or i dont know
### Related Configuration Files 
Create a Gist (https://gist.github.com/) for each configuration file related to this issue
https://gist.github.com/mrmauwurf/64fde077442a30116ac65303dc9bd0a0
[jobsets.txt](https://github.com/Erigitic/TotalEconomy/files/1902368/jobsets.txt)

**Comment by MarkL4YG** [comment] 2018-04-12 13:38
I would say there's an error with your configuration. Please check and include your server logs in order to see what the issue is.

**Comment by Erigitic** [comment] 2018-04-30 14:03
The file seems to be quite large, so I recommend removing everything from it and then one by one add them back until the error shows up again. This way we can narrow it down in order to easily determine the problematic set.

**Comment by Erigitic** [comment] 2018-05-04 14:30
@mrmauwurf Have you been able to try out what I said above? Or have you figured the issue out already? Thanks.

**Comment by mrmauwurf** [comment] 2018-05-04 15:58
I figured already its pams harvestry saplings without them all works and its seems that the saplings arent a normal place event so cant be used in this plugin.

**Comment by MarkL4YG** [comment] 2018-05-06 00:34
That's actually interessting... I would say your config would not be broken by an item with this behavior.
Can you investigate further?

**Comment by Erigitic** [comment] 2018-05-24 15:39
@mrmauwurf Were you able to investigate this issue anymore? If so did you get it figured out and can I close this issue now? Thanks.

**Comment by MarkL4YG** [comment] 2018-11-02 08:45
At this point I would say that this issues is stale.

**Closed** 2018-11-02 20:48 UTC
