### ISSUE TITLE
Bow kill no coins - "Reduce" coins command - Delay function

### ISSUE THREAD

**Issue by yololetsplay** [Erigitic/TotalEconomy#98] opened 2016-09-29 10:17 UTC
Hi there,

I created the job hunter... earning coins for killing the mobs works, but:
If I kill an mob with the bow I earn no money.

Can u fix this please or tell me how to force that problem?

Also can you please add a command to "reduce" player coins manually?
I work with the nucleus plugin where you can pay for using an command.
As OP I finally do not pay any money, so I would manually reduce the coins.

Another problem is that e.g. as farmer you can "place carrot" or something and cut it down instant and earn coins for it.
Is it possible do add an delay between getting coins for doing something like place and cut down carrots?
I hope u understand me :]

Greetz,
Hannes

**Comment by MarkL4YG** [comment] 2016-09-29 12:17
You don't get money or just no notification ?

**Comment by yololetsplay** [comment] 2016-09-29 12:31
No money and no EXP.

**Comment by Erigitic** [comment] 2016-09-29 15:08
I am pretty sure this is caused by the way we are checking the cause of death. Currently we are checking to see if a Player killed a mob. But, if a bow is used, I believe the cause of death would be the arrow and not the player.

Regarding the command to remove money, you just need to use the pay command from console. Ex: pay [USER] -10. This will remove 10 from the player's balance. Currently there is no way to remove money from a player's balance from within game. Are you wanting to remove money from a player's balance from within game vs from the console?

Lastly, regarding farming and being able to place down a crop and instantly break it to earn exp and money. This is a known issue and it will be fixed in an upcoming version.

**Comment by yololetsplay** [comment] 2016-09-29 15:18
Thx for ur replay Erigitic :]
About the bow problem: What I currently could try in config? Is there any way to pay bow kills?
Anyway, using /pay -10 or /adminpay -10 does not work "The amount must be positive", so that's not possible :/
I'd like to remove money ingame and also from console. Can you also make it possible to add and remove money also if the player is offline?
It's good to know you already know the problem about farming instant money.

**Comment by Erigitic** [comment] 2016-09-29 15:21
At the moment there is nothing you can do about bow kills. That has to be done on our end. And I am aware that the pay and adminpay commands do not work in game, that is intended. Removing money only works in the CONSOLE using the pay command. But we can definitely make it an option to remove money using the admin pay command. Regarding offline players, this may be a possibility as well.

**Comment by yololetsplay** [comment] 2016-09-29 15:23
Oh I tried /pay -10 ingame, sorry. In console it works great! That's pretty cool, thx for inform me :]

**Comment by yololetsplay** [comment] 2016-09-29 15:25
Is there any command to see the balance of players? It's annoying if u always need to open the accounts file.

**Comment by Erigitic** [comment] 2016-09-29 15:25
Of course! I went ahead and split up this issue into smaller issues so we can get these changes made. Thanks for submitting the report.

And yes there is, you can use /vbal [USER]

**Comment by yololetsplay** [comment] 2016-09-29 15:25
Fine, thx alot!

**Closed** 2016-09-29 15:25 UTC
