### ISSUE TITLE
Issue with the shop system

### ISSUE THREAD

**Issue by Witchcrafter1** [Erigitic/TotalEconomy#262] opened 2018-04-22 16:22 UTC
First of: there is already a issue with this content #260 
so if you dont need this, you could close this issue 

Sponge Version:  spongeforge-1.12.2-2611-7.1.0-BETA-2990
Forge Version:  forge-1.12.2-14.23.2.2611-universal
Total Economy Version:  TotalEconomy-1.8.0

### Description of issue

I dont know what the issue directly is.
I'm the admin of a server and i wanted to test the shops. So i create one, set some items, buy them and then delete the shop.

Now every time i want to join the server, the server crashs.
crash report below.

how to fix this?
how could i join without crashs?
is there a easy way? maybe delete something in a config file?
### Console errors
[crash-2018-04-22_16.11.14-server.txt](https://github.com/Erigitic/TotalEconomy/files/1935826/crash-2018-04-22_16.11.14-server.txt)

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by Joker4632** [comment] 2018-04-23 21:03
I've got exactly the same Problem and i have exactly the same Versions of Sponge/Forge/TotalEconomy.
The first Few Starts were no Problem. Now without any bigger change, the Server starts and after he is done he crashey immediately.
[crash-2018-04-23_20.50.57-server.txt](https://github.com/Erigitic/TotalEconomy/files/1940042/crash-2018-04-23_20.50.57-server.txt)

**Comment by Erigitic** [comment] 2018-04-23 21:45
Would you both mind copying and pasting your crash logs into a gist so I can take a look at them?

I plan on looking into this issue tonight, but for now I highly recommend, if possible, to remake the world and disable chest shops from within the main Total Economy configuration file.

**Comment by Joker4632** [comment] 2018-04-23 22:04
<script src="https://gist.github.com/Joker4632/58feda20b9a605c3f3a623b3be6dcedc.js"></script>

Hm creating an new World hm no Option for my Server :P I switched it to Single Player and deleted the chest-shops, copied back and crashes again. Also disabling the chest-shops doesn't prevent the crash.

**Comment by Witchcrafter1** [comment] 2018-04-23 22:11
@Joker4632

A fast fix is to Delete the player file inside the worlder folder. 

How to do that:
Find out the uuid of the player who created the shop. 

Destroy the shop in the world (if you doesn't have done it already) 

Go to your worlds folder
Then inside this folder to 
data/sponge
Inside this folder is a file with the uuid (the same as above) 

Delete this file, restart the server. 
Done.

**Comment by Witchcrafter1** [comment] 2018-04-23 22:14
https://gist.github.com/Witchcrafter1/d22941994b1713b90c9bee1a16a3dc8f#file-crash-server-shop-totaleconomy

**Comment by Joker4632** [comment] 2018-04-23 22:38
Hm the Location in the crash-report is a normal chest, but even if I delete this chest and all shops (using the Singleplayer) and deleting the Files (of the players who created shops and the one who created this chest), the server crashes again

**Comment by Witchcrafter1** [comment] 2018-04-23 22:52
Hmm

What I have done was:

Start the server without totaleconomy (leave the config) 

Start it with totaleconomy 

Still crashes when I want to join (I created the shop) 

Delete my player file 
(In world/playerdata/uuid) 
Delete my sponge player file 
(in world/data/sponge/uuid) 
Delete my player data in totaleconomy (I don't use a dB) 
(Config/totaleconomy/  player.conf?  Idk the name,  there where the Balance is stored,  with the uuid) 

@Joker4632

**Comment by Joker4632** [comment] 2018-04-23 22:59
Ok i could try it with removing all of this Files, but the Server crashes without anyone trying to join...
And the second is, the coordinates in the crash-report, points on a normal chest far away from the first steps on this Server. Don't make sense to me^^
But i will try.
Thx for the Help so far^^

**Comment by Witchcrafter1** [comment] 2018-04-23 23:01
Ok,  it seems that there are some more problems,  maybe a fix will help. 

Author works on that, like he said

**Comment by Erigitic** [comment] 2018-04-23 23:26
I quickly tested this out using the steps above and was not able to recreate the issue. Would you mind giving me a step by step of what you do, including the commands you run? This includes creating the claim and creating and stocking the shop.

**Comment by Joker4632** [comment] 2018-04-23 23:40
Puhh, the Problem there is the Server didn't crash while running. We played, stopped the Server over night and when we want to start him again her crashes.
Everybody has default Permissions, so he can use /shop buy, /shop stock (but only two Players including me have bought ah shop so far). 
Further they can use /balance (not view/top/set), /pay and /job. 

I can't remeber something that could have triggered that issue.

If you want to, i could zip the Server Folder and send it to you, cause i can't tell you the steps to reproduce

**Comment by Erigitic** [comment] 2018-04-24 14:53
Yeah, go ahead and zip it up and send it to me. Thanks.

**Comment by Erigitic** [comment] 2018-04-29 19:58
From the looks of it, the jar that you are both using doesn't seem to have the ShopKeys class, which doesn't make much sense. If possible, would you mind removing all the plugins except for Total Economy and check to see if the issue still occurs. I'd recommend duplicating your current server folder so you have a backup just in case.

**Comment by Joker4632** [comment] 2018-05-01 16:11
Sorry for the late answer. I removed all Mods and Plugins except Spongeforge and TotalEconomy and it works, awesome. But why ^^
I will try to find the problematic Mod/Plugin.

**Comment by Erigitic** [comment] 2018-05-01 23:06
Before I jump to any conclusion, would you mind adding each plugin/mod in one-by-one until the issue occurs again. I know this is tedious but this will help a tremendous amount when it comes to figuring out whether it's an issue with Total Economy or another mod/plugin. Thanks.

**Comment by Joker4632** [comment] 2018-05-04 13:04
So i had to do lot of Stuff last Days, but i checked all Mods and Plugins and found the problematic one.
It was Nucleus (https://ore.spongepowered.org/Nucleus/Nucleus). It overlaps with TotalEconomy with his Server-Shops, even though i did not activate this module of Nucleus.

**Comment by Erigitic** [comment] 2018-05-04 14:26
Did disabling that module in Nucleus fix the crashing issue? If so, is it ok to close this issue?

**Comment by MarkL4YG** [comment] 2018-05-06 00:31
Interessting. so far I've been using Nucleus without any issues.
Looks like I need to test this.

**Comment by CDAGaming** [comment] 2018-05-08 15:12
Same issue here @Erigitic any sign of a possible fix

**Comment by dualspiral** [comment] 2018-05-08 16:58
I think this is the same issue as this: https://github.com/trentech/ProjectPortals/issues/86#issuecomment-362788494

You need to register your keys during init.

**Closed** 2018-05-14 15:51 UTC
Labels: bug, high priority
