### ISSUE TITLE
Random missing money

### ISSUE THREAD

**Issue by Dysthymic** [Erigitic/TotalEconomy#95] opened 2016-09-16 01:54 UTC
We run a larger production server of around 60-100 players average.
We get reports of random players balance getting set to 0 or just missing large sums. It appears there may be a saving issue.
I have compared accounts.json files and they do indeed shrink at times by a couple thousand bytes.

**Comment by Erigitic** [comment] 2016-09-16 02:06
@Dysthymic I assume you mean accounts.conf as Total Economy does not utilize JSON files? Regardless, please provide the contents of the accounts.conf file.

**Comment by Dysthymic** [comment] 2016-09-16 05:57
http://pastebin.com/Wju28Pji

**Comment by Dysthymic** [comment] 2016-09-17 22:18
Issue is becoming more common as our file size gets larger. Getting numerous reports daily now.

**Comment by Dysthymic** [comment] 2016-09-17 22:21
My mistake as well it was accounts.conf that is what I meant. Sorry for the confusion.

My hypothesis is it has trouble saving. Our accounts config is fairly large. We have restarts scheduled hourly due to some issues with Pixelmon BETA Pokemon retrieve issues.

I believe it may be occurring during restarts. However, there are no errors on restart as I have checked this numerous times

**Comment by Erigitic** [comment] 2016-09-17 23:00
Thanks for all the information. This will make it a lot easier to figure out the cause of the issue. I will look into this over the next few days and see what I can figure out. Thanks again.

**Comment by Dysthymic** [comment] 2016-09-18 18:24
Thank you so much. Looking forward to it

**Comment by Erigitic** [comment] 2016-09-18 23:14
I believe I may have found a fix for this but I have no way of testing it because I can't recreate it. Would you mind testing on your end? Here is the link: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.5.1-DEV.

**Comment by Dysthymic** [comment] 2016-09-19 17:30
Thank you! Just uploaded it. I'll let you know if there are any more reports or not today

**Comment by Dysthymic** [comment] 2016-09-20 18:09
Hey just wanted to keep you updated:
The issue still happens but not as much. The reports have probably halved. We used to get 10-15 reports a day. Yesterday, we had 5 reports.

**Comment by Dysthymic** [comment] 2016-09-22 19:34
I've confirmed it only happens after a server restart. There is some sort of save issue.

**Comment by MarkL4YG** [comment] 2016-09-23 12:36
Do you have a custom start/stop/restart script? If so: Can we take a look at it?

**Comment by Erigitic** [comment] 2016-09-26 02:04
@Dysthymic I have one more idea on how to solve this. Also, as @MarkL4YG asked, if you do happen to have any sort of custom start/stop/restart script that you use then please share it with us so we can understand the restart process. Thanks and hopefully we can get this figured out soon as this is obviously a big issue.

**Comment by Erigitic** [comment] 2016-09-26 17:03
@Dysthymic Give this a shot: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.5.1-DEV. Hopefully this will work.

**Comment by Erigitic** [comment] 2016-09-30 16:05
@Dysthymic Have you been able to test this yet?

**Comment by Dysthymic** [comment] 2016-09-30 22:18
Deepest apologies, I was moving and away for a few days.
We have no advanced custom script- basically it just runs the command /stop and 1 minute later it starts the jar to start the server again

We have been using  https://github.com/Erigitic/TotalEconomy/releases/tag/v1.5.1-DEV for approximately 11 days and still experiencing the same issues

**Comment by Erigitic** [comment] 2016-09-30 22:52
Give this updated version a shot: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.5.1-DEV. Is this still only happening when the server restarts?

**Comment by Dysthymic** [comment] 2016-10-03 20:05
Updated to it yesterday and we still are experiencing this issue

**Comment by Erigitic** [comment] 2016-10-05 18:04
I have no idea why this is happening.  I will look into it more and see if I can come up with something.

**Comment by MarkL4YG** [comment] 2016-10-07 08:52
@Dysthymic 
Can you tell us a bit more about your setup? 
* What other plugins and mods do you use?
* Which Sponge version are you running?
* Do you have any plugins running that do transactions automatically?

Oh and also a little speculation:
Try to figure out, if the players who reported missing money recently changed their displayName (nickname) ingame and/or their username via mojang.com

**Comment by Dysthymic** [comment] 2016-10-12 16:36
Hey,
We are now using Sponge 1794 (we were using 1692). Issue still occurs.
We are using Pixelmon with their Economy Bridge sidemod to sync PokeDollars. What I am thinking is it may be the flatfile system. It may have a hard time looking through the incredibly long file for all the players at one time. We often have 70 to 100 players online at once. It may be more efficient to do a database perhaps? Just my speculation.

**Comment by MarkL4YG** [comment] 2016-10-14 19:02
@Dysthymic TotalEconomy uses Configurate which loads the HOCON-config into the RAM.
Thus the file on the disk is not being touched unless loaded or saved.

But imo taking a look at the Economy Bridge might be worth a shot. Maybe it interfers with the account management of TE in some way.

**Comment by Erigitic** [comment] 2016-11-24 01:08
It's been a while, but does this issue still persist @Dysthymic?

**Closed** 2017-03-01 16:29 UTC
