### ISSUE TITLE
Exception when connecting

### ISSUE THREAD

**Issue by LemADEC** [Erigitic/TotalEconomy#178] opened 2017-05-30 22:39 UTC
As of 1.6.0-DEV & spongeforge-1.11.2-2282-6.1.0-BETA-2357, an exception is raised when players connects to the server:
```
[18:29:31] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.6.0-DEV, description=All in one economy plugin for Minecraft/Sponge, source=/home/mischief/./plugins/TotalEconomy-v1.6.0-DEV.jar}
java.lang.NullPointerException
>       at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_121]
>       at com.erigitic.main.TotalEconomy.getStartingBalance(TotalEconomy.java:348) ~[TotalEconomy.class:?]
>       at com.erigitic.config.TEAccount.getDefaultBalance(TEAccount.java:80) ~[TEAccount.class:?]
>       at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:154) ~[AccountManager.class:?]
>       at com.erigitic.main.TotalEconomy.onPlayerJoin(TotalEconomy.java:190) ~[TotalEconomy.class:?]
>       at org.spongepowered.common.event.listener.JoinListener_TotalEconomy_onPlayerJoin24.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2282-6.1.0-BETA-2357]
>       at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1617) [mt.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262) [NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211) [NetworkDispatcher$1.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [er.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

any chance we get a 1.11 version of the plugin?

**Comment by Erigitic** [comment] 2017-05-30 23:36
Total Economy will be updated for 1.11. Because this error occurred on a build that Total Economy was not made for, there's a good chance it is caused by that.

**Comment by LemADEC** [comment] 2017-05-31 00:01
Sounds like we need to find another economy plugin I guess

**Comment by Erigitic** [comment] 2017-05-31 00:18
@LemADEC Here's an updated version that was tested on 1.11.2. No error was encountered so it should be fixed. Let me know how it works for you. Thanks.

https://github.com/Erigitic/TotalEconomy/releases/tag/v1.6.0-DEV

**Comment by LemADEC** [comment] 2017-05-31 00:32
Issue remains:
```
[20:25:02] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.6.0-DEV, description=All in one economy plugin for Minecraft/Sponge, source=/home/mischief/./plugins/TotalEconomy-1.6.0-alpha.6.jar}
java.lang.NullPointerException
>       at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_121]
>       at com.erigitic.main.TotalEconomy.getStartingBalance(TotalEconomy.java:315) ~[TotalEconomy.class:?]
>       at com.erigitic.config.TEAccount.getDefaultBalance(TEAccount.java:80) ~[TEAccount.class:?]
>       at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:165) ~[AccountManager.class:?]
>       at com.erigitic.main.TotalEconomy.onPlayerJoin(TotalEconomy.java:194) ~[TotalEconomy.class:?]
>       at org.spongepowered.common.event.listener.JoinListener_TotalEconomy_onPlayerJoin24.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2357]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2282-6.1.0-BETA-2357]
>       at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1617) [mt.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262) [NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211) [NetworkDispatcher$1.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [er.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Erigitic** [comment] 2017-05-31 00:39
Looks like you need to remake your main configuration file. The main config was changed with this recent version. Just remove it then restart the server and you should be good to go.

**Comment by LemADEC** [comment] 2017-05-31 01:19
ok, it works now, thanks!

**Comment by MarkL4YG** [comment] 2017-05-31 12:48
It looks like I need to apologize for not reporting an issue I discovered and fixed in my local workspace.
That issue occurs because TotalEconomy doesn't use fallback values on some occasions when reading from the config.
In this case ``#getNode("currency", "startbalance").getString()`` reads null (which cannot be turned into a BigInteger) because of the plugin using another path since one of the last updates and not re-initializing the configuration due to its existence therefore the value exists only in its old location and cannot be read from the new one.

**Closed** 2017-05-31 22:03 UTC

**Comment by Erigitic** [comment] 2017-05-31 22:05
I feel like notifying the server owner of an outdated configuration file would be more helpful in order to avoid this issue, and others that might arise from an outdated config, constantly occurring. Thoughts?

**Comment by LemADEC** [comment] 2017-06-01 00:24
There's no warranty the server owner will catch the issue unless you do a forced crash or cancel the plugin loading up. Doing so would prevent to see the updated file to do the conversion, forcing to do 2 additional server restarts to fix it.

Hence, in my opinion, converting the previous key to the new one is the preferred way.

**Comment by MarkL4YG** [comment] 2017-06-01 08:21
@Erigitic An idea would be the following;
* Explicit notices in ChangeLogs (stating what changed) __should__ suffice since administrators are obligated to read those
* Integer identifying the configuration version (when syntax changes build no. goes up). This way we can notify server owners of a change in case they missed the former
* Fallback (supported by Configurate) values to prevent the plugin from throwing exceptions ___OR___ refusing to load the plugin when the configuration version doesn't match.

@LemADEC In my opinion (and probably also the of many server administrators) when updating any plugin ChangeLogs have to be read in order to be aware of any changes in behavior or even dependencies.  
There's no excuse for just blindly downloading a jar with a higher version and then complaining about not knowing stated changes.

**Comment by LemADEC** [comment] 2017-06-01 18:47
@MarkL4YG you can't expect users to read all change logs, especially when several versions have elapsed.
Even if they read them, you can't expect them to catch all the consequences.
In other words, we're humans, we're prone to make mistakes.

In other words, when designing a product, labeling or writing documentation like change logs should be the very last line of defense. The main proper way to address an issue is prevent it's occurrence in the first place.

**Comment by MarkL4YG** [comment] 2017-06-01 20:36
@LemADEC TE has a very low release rate, all changelogs are brief and can be found on the same page.  So yes, I can expect proper server administrators to read changelog.  
Bigger releases may highlight breaking changes for instant notice and as I said it's a good idea to also add fallback values to prevent exceptions. But it's a worse idea to write extra code for each little change just for conversion.
I'd do that for jobsets when the configs are potentially huge but not for any node in the main configuration. This would unnecessarily blow up the code files or (if you'd remove one conversion when the next change to it arrives) would break immediately when a version is skipped.  

Also yes: It's better to prevent breaking changes but sometimes those are necessary.

**Comment by Erigitic** [comment] 2017-06-01 21:28
I went ahead and added a notice to the 1.6.0 dev release stating that configuration changes have been made. As well as that, build numbers have started being used to better identify new releases. 

@LemADEC Do note that Total Economy is still a work in progress so the structure of the main configuration file will change occasionally. And adding a bunch of code to check and make sure that the main configuration file is proper is really not necessary in my opinion because at some point, config breaking updates will no longer be made. As well as that, config breaking updates don't really happen that often. With that said, a default value will be added so that error does not pop up. This does not fix the error though, just silences it.
