### ISSUE TITLE
Error when paying player for killing a mob

### ISSUE THREAD

**Issue by TheJackah** [Erigitic/TotalEconomy#248] opened 2018-02-21 00:12 UTC
Sponge Version:  7.1.0-SNAPSHOT-dfc5c4a7 / 1.12.2-7.1.0-BETA-10
Forge Version:  N/A
Total Economy Version:  1.7.1 (API 7)

### Description of issue
When a player kills a mob, the money is not added to their /bal. In console, an error is shown related to the listener for when an entity is killed.

### Console errors

```
[00:03:16] [Server thread/ERROR] [Sponge]: Could not pass DestructEntityEvent$Death$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.7.1-API_7, description=All in one economy plugin for Minecraft/Sponge, source=mods/TotalEconomy-1.7.1-API_7.jar}
java.lang.NullPointerException: null
at com.erigitic.jobs.JobManager.onPlayerKillEntity(JobManager.java:906) ~[JobManager.class:?]
at org.spongepowered.common.event.listener.DeathListener_JobManager_onPlayerKillEntity69.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-10]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:403) [SpongeEventManager.class:1.12.2-7.1.0-BETA-10]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:430) [SpongeEventManager.class:1.12.2-7.1.0-BETA-10]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-7.1.0-BETA-10]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-10]
at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:679) [SpongeCommonEventFactory.class:1.12.2-7.1.0-BETA-10]
at net.minecraft.entity.EntityLivingBase.func_70645_a(SourceFile:2619) [vp.class:?]
at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(SourceFile:58) [adk.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(SourceFile:2889) [vp.class:?]
at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:67) [ade.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71059_n(SourceFile:3319) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(SourceFile:1224) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(SourceFile:2308) [pa.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.1.0-BETA-10]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkh000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-10]
at net.minecraft.server.MinecraftServer.redirect$onRun$zim000(SourceFile:4179) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

### Steps to reproduce
1. Kill a mob that awards money, e.g skeleton
2. No money is added to /bal.
3. Error appears in console.

**Comment by MarkL4YG** [comment] 2018-02-21 06:59
Please put your account configuration and a full server log into a gist so I can take a look at that.

**Comment by TheJackah** [comment] 2018-02-21 19:18
@MarkL4YG - here's the gist: https://gist.github.com/TheJackah/2a73a9a64a8bd11675281383a74c01d5

We use the SQL storage option, so I've also included the accounts.sql.

**Comment by MarkL4YG** [comment] 2018-02-21 20:10
Thanks for providing such detail!  

But:
Did your server log get rotated? ``[00:00:02]``?
I wanted to take a look at the server startup in order to see if the SQL connection failed for some reason.

**Comment by MarkL4YG** [comment] 2018-02-21 20:16
Nevermind. I think I found the cause: https://github.com/Erigitic/TotalEconomy/blob/api-7/src/main/java/com/erigitic/jobs/JobManager.java#L906 .
When SQL is used the ``accountConfig`` is (obviously) ``null`` ¯\\\_(ツ)\_/¯.
Seems like we forgot to respect that in this event.  

@Erigitic Could you take a look if this is fixed in the code for 1.8 and maybe push the fix if needed?

**Comment by TheJackah** [comment] 2018-02-21 20:54
Thanks @MarkL4YG - hopefully fixed soon, we'd love to be able to use the plugin. :)

**Comment by Erigitic** [comment] 2018-02-23 18:00
I will get this added into 1.8.0 before release.

**Closed** 2018-02-26 16:47 UTC
