### ISSUE TITLE
Set balance not working (or maybe balance not working?)

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#159] opened 2017-03-19 00:39 UTC
Using the `/setbalance` command will not add money to the player's balance. Look:

![1](http://image.prntscr.com/image/f0d0f4cdcad741beab4f929327c62aeb.png)

Using:
```
   Minecraft: 1.10.2
   SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
   SpongeForge: 1.10.2-2254-5.2.0-BETA-2231
   Minecraft Forge: 12.18.3.2239
   TotalEconomy 1.5.3
```

**Comment by MarkL4YG** [comment] 2017-03-19 08:13
1. I bet this is resolvable by changing your currency back to "$" (Dollars/Dollar)
2. If not, pin your configs. (e.g. by using [hastebin](http://hastebin.com)).

**Comment by Eufranio** [comment] 2017-03-20 00:11
Nope, that will not fix the issue. Config: https://hastebin.com/lamaneyuho.bash

**Comment by Erigitic** [comment] 2017-03-20 04:09
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/7hQ7N9US/7-test)

**Comment by Erigitic** [comment] 2017-03-20 04:11
This is a duplicate of #155. Go into your accounts.conf file and change the "dollar-balance" to "[YOUR-CURRENCY]-balance" for all accounts.

**Closed** 2017-03-20 04:12 UTC

**Comment by MarkL4YG** [comment] 2017-03-20 10:41
Don't tell me the currency is case-sensitive 🙈 ... @Eufranio rename the configs currency to all lowercase dollar/dollars (oh and the order here is singular/plural by the way - the config you pasted has it mixed up) and tell us if it's working.

**Comment by Erigitic** [comment] 2017-03-20 20:30
I think it is. This should be forced to lowercase, at least in terms of the accounts configuration file.

**Comment by MarkL4YG** [comment] 2017-03-21 20:46
Yeah I think at least internally this should all be handled lowercase.
