### ISSUE TITLE
Multi-currency Sponge 1.10.2/1.12.2

### ISSUE THREAD

**Issue by Krosta8** [Erigitic/TotalEconomy#214] opened 2017-10-24 11:35 UTC
Hello,
I have a problem with multi-currency support.
I want to use it for two currencies with VirtualChest and I can’t get it to work properly. Everytime its using the first currency.
And with PlaceHolderAPI I can’t get the value of the currencies properly. I tried to use %economy_balance_token% and %economy_balance_kredit% then %economy_balance_[token]% and %economy_balance_[kredit]%. Again, its just get back the balance of the first currency.

Does anyone know the solution for this?

I'm using Sponge 1.10.2 API 5.2.0
I tried Total Economy 1.7.1 and Total Economy 1.7.0 for API 5.2.0.

Everything else works correctly.

Is there possibly way how to do "money take Krosta8 100 token" which should take me 100 tokens from my account?

Furthermore, I would like to use your plugin on my second server with Sponge API 7.0.0 too. In which phase is the development? (I don't need the jobs for this API)

Thank you very much,
Krosta8

**Comment by MarkL4YG** [comment] 2017-10-24 15:56
For the API 7 status see the corresponding issue.

For the currency stuff please provide your ``totaleconomy.conf`` and possibly also your server logs.
I'd recommend using Github-Gists or hastebin. Although the lifetime of hastebin docs is pretty short.

**Comment by Krosta8** [comment] 2017-10-24 16:21
Here is the config, but there is no problem, i think. I can normally do every command, but I can't get it to work with PlaceHolderAPI.
https://pastebin.com/9u8LpMYt
Everytime it just shows the default currency.

**Comment by MarkL4YG** [comment] 2017-10-24 16:25
Regarding placeholders I'd say it's an issue between the bridge and the Sponge Economy API and not related to TE until proven otherwise ^^''

Currency names are fully lowercase in the config!

**Comment by Krosta8** [comment] 2017-10-24 17:01
Ok, thank you.
Btw, is there any other option how to shows in Scoreboard (and so on) my own balance?

**Comment by MarkL4YG** [comment] 2017-10-24 17:14
That's outside of TEs focus. You may search for other alternative plugins though.

You may also contact the plugins dev and ask if they support multi-currency.

**Comment by Krosta8** [comment] 2017-10-24 17:16
Okay,
thank you a lot 🙂

**Comment by Erigitic** [comment] 2017-10-24 21:24
@Krosta8 Regarding API7 support, I've just released a stable build for it on the Ore page: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.7.1-API_7.

**Comment by Krosta8** [comment] 2017-10-24 21:29
Very nice! 
I just have one question.
I can do "/adminpay Krosta8 -80 currency" and the final amount can by below 0. Is this a mistake? Because I need to run command from Virtualchest which should remove the amount from players account.
Or to be able to do something like "/pay Console amount currency".

Is anything from that possible?

Thank you a lot! :relaxed:

**Comment by Erigitic** [comment] 2017-10-24 21:45
This is intended behavior for the adminpay command. At the moment, there is nothing else that can be used to remove money from a player's balance, unless you used the set balance command but I don't think that would be of any use to you in this case. I have no experience with VirtualChests so it is kind of hard to give you an alternative solution. Sorry.

**Comment by Krosta8** [comment] 2017-10-25 04:43
Okay, thank you a lot anyway :relaxed:

**Comment by Erigitic** [comment] 2017-10-26 20:49
@Krosta8 Can I go ahead and close this issue or do you still need help with it?

**Comment by Krosta8** [comment] 2017-10-26 21:32
Oh, sorry, I forgot it. 
I contacted author of PlaceHolderAPI and the problem is on his side, so sorry for this issue on your github and thank you for your time.

I just hope for the take command. :relaxed:

Thank you a lot!

**Comment by Erigitic** [comment] 2017-10-27 03:00
It may be a possibility that we'll add a parameter to the admin pay command in order to prevent the receiving player's balance from going negative. Thanks for submitting the issue.

**Closed by Erigitic** 2017-10-27 03:00 UTC
