### ISSUE TITLE
BC Quarry Exception

### ISSUE THREAD

**Issue by JoeSchmo2840** [Erigitic/TotalEconomy#47] opened 2016-01-27 06:02 UTC
Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=TotalEconomy, name=Total Economy, version=1.3.0}

**Comment by Erigitic** [comment] 2016-01-27 06:38
Is there anymore to that error log? If there is please send it.

**Comment by JoeSchmo2840** [comment] 2016-01-27 21:06
Sorry here is the whole exception.

http://pastebin.com/bBrgG6HN

**Comment by Erigitic** [comment] 2016-01-27 21:08
I will check this out on my end right now. Thanks for the log.

**Comment by Erigitic** [comment] 2016-01-27 21:18
What exactly did you do that caused this error to occur? Can't seem to recreate it on my end.

**Comment by JoeSchmo2840** [comment] 2016-01-27 21:32
It seems to happen when a Buildcraft Quarry is running. Also I am getting: "Entity is not registered EntityMechanicalArm['unknown'/35324, l='world', x=252.00, y=80.00, z=242.00]" so Im thinking thats whats bugging TE

**Comment by Erigitic** [comment] 2016-01-27 21:36
Ok that makes sense. I will have to do some better error checking on my end to make sure that player is the one who is actually breaking the blocks. I will get this fixed today. Thanks for bringing this up.

**Comment by JoeSchmo2840** [comment] 2016-01-27 21:38
Awesome, glad I could help. Im running a testing server once again. So if I find anymore Ill let you know.

**Comment by Erigitic** [comment] 2016-01-27 21:39
Good to hear. I am trying to fix/change a bunch of things in order to make Total Economy compatible with mods and stuff like this helps out a lot.

**Comment by MarkL4YG** [comment] 2016-04-24 09:11
You can probably close this as I was unable to reproduce the issue.

**Closed** 2016-04-29 01:47 UTC
Labels: bug
