### ISSUE TITLE
NPE with api7

### ISSUE THREAD

**Issue by hunter688** [Erigitic/TotalEconomy#208] opened 2017-09-23 10:31 UTC
Compiled api7 branch. When start server got NPE:

https://pastebin.com/BUhaiVpk

**Comment by hunter688** [comment] 2017-09-23 10:51
When player join to server got another NPE:

https://pastebin.com/uVb4f3pP

**Comment by MarkL4YG** [comment] 2017-09-23 11:31
Duplicate of #204 #207

**Comment by MarkL4YG** [comment] 2017-09-23 11:33
Please be aware that TotalEconomy currently only supports API 5 and 6 and API 7 development has just begun. Please also keep in mind that SpongeAPI 7 is an experimental release which means that the API can change upon any commit.

**Comment by hunter688** [comment] 2017-09-23 12:45
Hmm, I made some debug and create some "fixes".

problems are with registering currency from config file and registerlisteners.

My "fixed" temporary solution:

<pre>
diff --git a/src/main/java/com/erigitic/main/TotalEconomy.java b/src/main/java/com/erigitic/main/TotalEconomy.java
index 740565f..b41a093 100644
--- a/src/main/java/com/erigitic/main/TotalEconomy.java
+++ b/src/main/java/com/erigitic/main/TotalEconomy.java
@@ -39,6 +39,7 @@ import ninja.leaping.configurate.loader.ConfigurationLoader;
 import org.slf4j.Logger;
 import org.spongepowered.api.Game;
 import org.spongepowered.api.Server;
+import org.spongepowered.api.Sponge;
 import org.spongepowered.api.command.args.GenericArguments;
 import org.spongepowered.api.command.spec.CommandSpec;
 import org.spongepowered.api.config.ConfigDir;
@@ -164,7 +165,8 @@ public class TotalEconomy {
     @Listener
     public void init(GameInitializationEvent event) {
         createAndRegisterCommands();
-        registerListeners();
+        //registerListeners();
+        Sponge.getEventManager().registerListeners(this, jobManager);
     }
 
     @Listener
@@ -307,7 +309,13 @@ public class TotalEconomy {
             boolean prefixSymbol = currencyNode.getNode("prefix-symbol").getBoolean();
             boolean isTransferable = currencyNode.getNode("transferable").getBoolean();
             BigDecimal startBalance = new BigDecimal(currencyNode.getNode("startbalance").getDouble());
-
+            currencySingular="Dollar";
+            currencyPlural="Dollars";
+            currencySymbol="$";
+            isDefault = true;
+            prefixSymbol = true;
+            isTransferable = true;
+            startBalance = new BigDecimal(100);
             TECurrency currency = new TECurrency(
                     Text.of(currencySingular),
                     Text.of(currencyPlural),
</pre>

**Comment by MarkL4YG** [comment] 2017-09-23 13:22
Well... either you wait for the next development release to support API 7 or you dig completely into the code and submit a PR ^^

**Comment by Erigitic** [comment] 2017-09-23 14:21
https://github.com/Erigitic/TotalEconomy/issues/209

**Closed by Erigitic** 2017-09-23 14:21 UTC
