### ISSUE TITLE
Baltop 1.10.2 not working

### ISSUE THREAD

**Issue by Dysthymic** [Erigitic/TotalEconomy#94] opened 2016-09-16 01:52 UTC
Command does not work on your latest build

**Comment by Erigitic** [comment] 2016-09-16 02:05
@Dysthymic Please provide an error log.

**Comment by Dysthymic** [comment] 2016-09-16 05:59
http://pastebin.com/bWPT7i5p

**Comment by Erigitic** [comment] 2016-09-16 16:12
I am pretty sure this is being caused by the player/players being offline. I have to modify some code to get baltop to work with offline players. Thanks for submitting the bug report.

**Comment by Erigitic** [comment] 2016-09-16 21:00
This has been fixed and will be released in v1.5.1. Thanks again for submitting the report.

**Comment by MarkL4YG** [comment] 2016-09-17 11:10
FYI: [This (SpongeDocs)](https://docs.spongepowered.org/master/en/plugin/offline-userplayer-data.html) may be a solution that doesn't require to perform a request to mojang each time a player's just not online anymore

**Comment by Erigitic** [comment] 2016-09-17 15:16
If this works, I like this solution better. Going to reopen and switch it over. Thanks for the help as usual @MarkL4YG .

**Comment by MarkL4YG** [comment] 2016-09-17 16:08
@Erigitic You're welcome of course it it does :)
But: If it doesn't let me know since I wrote that article ':D

**Comment by Erigitic** [comment] 2016-09-26 18:28
@MarkL4YG I could be doing something wrong but userStorage is always null:

`Optional<UserStorageService> userStorage = Sponge.getServiceManager().provide(UserStorageService.class);`

**Comment by JonathanxD** [comment] 2016-09-27 10:49
The `UserStorageService` is only available after `Server` instance being available, try to get the service in `GameStartedServerEvent` phase.

**Comment by Erigitic** [comment] 2016-09-27 17:43
Continues to be null regardless of where I initialize it.

**Comment by JonathanxD** [comment] 2016-09-27 18:06
I don't known why is null.
I used the service in my plugin and it worked: [wReport](https://github.com/JonathanxD/wReport/blob/development/src/main/java/io/github/jonathanxd/wreport/wReport.java#L227), I will try in latest build.

**Comment by JonathanxD** [comment] 2016-09-27 18:49
This is working on `5.0.0-BETA-1756`.

**Comment by MarkL4YG** [comment] 2016-09-28 17:55
@Erigitic where do you try to retrieve the USS ? 
And what revision of Sponge are you building/testing against ?

**Comment by Erigitic** [comment] 2016-09-29 04:48
@MarkL4YG I have tried in both the preInit and onServerStart functions. And tested against spongeforge-1.10.2-2073-5.0.0-BETA-1707 and using SpongeAPI version 5.0.0-SNAPSHOT.

**Comment by MarkL4YG** [comment] 2016-09-29 12:20
@Erigitic before messing around with everything, try to get the USS within a command handler and see if that works since this can tell you whether it it's even initialized somewhere or not.

**Comment by Erigitic** [comment] 2016-09-29 16:09
@MarkL4YG I figured it out and it works and always has worked. For testing purposes I added another UUID into the accounts config and just realized that the USS only works with accounts that have logged into the server at least once. Removed that UUID and it worked.

**Comment by MarkL4YG** [comment] 2016-10-02 12:54
``totalEconomy.getUserStorageService().get().get(uuid).get().getName()``
can be shortened to
``totalEconomy.getUserStorageService().get(uuid).get().getName()``
if you use ``.provideUnchecked`` [here](https://github.com/Erigitic/TotalEconomy/commit/7cce718bd95cd62408e6db2489c888ed604cf2f4#diff-c37bc4f626ffea2ff06f23fa306987a6R148).

Also: (Side-)Note that you use "get without isPresent" which may cause problems when you try to get the displayname of never connected accounts such as virtual accounts that do not represent a specific player :)

**Closed** 2016-11-24 00:41 UTC
Labels: bug
