### ISSUE TITLE
Transaction Failed when trying to sell a item with AdminShop

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#158] opened 2017-03-19 00:32 UTC
When trying to sell a item with AdminShop, this message will appear in the chat:

![1](http://image.prntscr.com/image/8513259f6a6c4463b6fd38ea481eb25a.png)

Testing with EconomyLite it works, with TotalEconomy it does not. Anything I can do about it?

Running:
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2231
    Minecraft Forge: 12.18.3.2239
    TotalEconomy 1.5.3

**Comment by MarkL4YG** [comment] 2017-03-19 08:14
Try solution 1 of #159

**Comment by Eufranio** [comment] 2017-03-20 00:11
Didn't fix the issue.

**Comment by Erigitic** [comment] 2017-03-20 04:13
Please send the accounts.conf file in a pastebin as well as the main config file. I believe this is a duplicate of #155.

**Closed** 2017-03-26 06:02 UTC
